### ISSUE TITLE
Panic in light nodes

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#1383] opened 2023-03-02 16:35 UTC
In the latest devnet run a panic was hit by light nodes:

```
Feb 23 17:42:53 light1 nimiq-client[52854]: 2023-02-23T17:42:53.964347239Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'We expected a request for this peer': consensus/src/sync/light/sync_stream.rs:196
Feb 23 17:42:53 light1 nimiq-client[52854]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Feb 23 17:42:53 light1 nimiq-client[52854]:    1: log_panics::Config::install_panic_hook::{{closure}}
Feb 23 17:42:53 light1 nimiq-client[52854]:    2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:2002:9
Feb 23 17:42:53 light1 nimiq-client[52854]:       std::panicking::rust_panic_with_hook
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:692:13
Feb 23 17:42:53 light1 nimiq-client[52854]:    3: std::panicking::begin_panic_handler::{{closure}}
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:577:13
Feb 23 17:42:53 light1 nimiq-client[52854]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:137:18
Feb 23 17:42:53 light1 nimiq-client[52854]:    5: rust_begin_unwind
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:575:5
Feb 23 17:42:53 light1 nimiq-client[52854]:    6: core::panicking::panic_fmt
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/core/src/panicking.rs:64:14
Feb 23 17:42:53 light1 nimiq-client[52854]:    7: nimiq_consensus::sync::light::sync_stream::<impl futures_core::stream::Stream for nimiq_consensus::sync::light::sync::LightMacroSync<TNetwork>>::poll_next
Feb 23 17:42:53 light1 nimiq-client[52854]:    8: futures_util::stream::stream::StreamExt::poll_next_unpin
Feb 23 17:42:53 light1 nimiq-client[52854]:    9: <nimiq_consensus::consensus::Consensus<N> as core::future::future::Future>::poll
Feb 23 17:42:53 light1 nimiq-client[52854]:   10: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
Feb 23 17:42:53 light1 nimiq-client[52854]:   11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Feb 23 17:42:53 light1 nimiq-client[52854]:   12: tokio::runtime::task::core::Core<T,S>::poll
Feb 23 17:42:53 light1 nimiq-client[52854]:   13: tokio::runtime::task::harness::Harness<T,S>::poll
Feb 23 17:42:53 light1 nimiq-client[52854]:   14: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Feb 23 17:42:53 light1 nimiq-client[52854]:   15: tokio::runtime::scheduler::multi_thread::worker::Context::run
Feb 23 17:42:53 light1 nimiq-client[52854]:   16: tokio::macros::scoped_tls::ScopedKey<T>::set
Feb 23 17:42:53 light1 nimiq-client[52854]:   17: tokio::runtime::scheduler::multi_thread::worker::run
Feb 23 17:42:53 light1 nimiq-client[52854]:   18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Feb 23 17:42:53 light1 nimiq-client[52854]:   19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Feb 23 17:42:53 light1 nimiq-client[52854]:   20: tokio::runtime::task::harness::Harness<T,S>::poll
Feb 23 17:42:53 light1 nimiq-client[52854]:   21: tokio::runtime::blocking::pool::Inner::run
Feb 23 17:42:53 light1 nimiq-client[52854]:   22: std::sys_common::backtrace::__rust_begin_short_backtrace
Feb 23 17:42:53 light1 nimiq-client[52854]:   23: core::ops::function::FnOnce::call_once{{vtable.shim}}
Feb 23 17:42:53 light1 nimiq-client[52854]:   24: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:1988:9
Feb 23 17:42:53 light1 nimiq-client[52854]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:1988:9
Feb 23 17:42:53 light1 nimiq-client[52854]:       std::sys::unix::thread::Thread::new::thread_start
Feb 23 17:42:53 light1 nimiq-client[52854]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys/unix/thread.rs:108:17
Feb 23 17:42:53 light1 nimiq-client[52854]:   25: start_thread
Feb 23 17:42:53 light1 nimiq-client[52854]:   26: clone
Feb 23 17:42:53 light1 nimiq-client[52854]:
```

**Comment by jsdanielh** [comment] 2023-03-02 16:37
@viquezclaudio Is this related to #1264?

**Comment by viquezclaudio** [comment] 2023-03-02 17:20
Closing as duplicate of #1264

**Closed as completed by viquezclaudio** 2023-03-02 17:20 UTC
