### ISSUE TITLE
Allow paging for transactions-by-address queries

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#2733] opened 2024-07-09 16:49 UTC
As @paberr recently discovered, the tree structure we use for the transaction store lends itself to efficiently request transactions with an offset.

This option should be added to the RPC API, and then to the relevant protocol message.

- [ ] offset in RPC `get_transactions_by_address`
- [ ] offset in protocol receipts message

The change to the message will be a protocol breaking change.

**Comment by paberr** [comment] 2024-07-12 15:38
I think this is a duplicate of #2697

**Closed as completed** 2024-10-14 19:32 UTC
Labels: enhancement
