### ISSUE TITLE
Panic in history sync: "Agent should be present"

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#250] opened 2021-04-07 09:27 UTC
This happened to seed1 in the docker setup when trying to sync with an external node, starting and stopping that node because it didn't start to sync.

```
seed1_1    |  2021-04-07 09:25:06 ERROR request_response     | Timeout
seed1_1    |  2021-04-07 09:25:06 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Agent should be present': /build/consensus-albatross/src/sync/history.rs:676
seed1_1    |    0: log_panics::init::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
seed1_1    |    1: std::panicking::rust_panic_with_hook
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:595:17
seed1_1    |    2: std::panicking::begin_panic_handler::{{closure}}
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:497:13
seed1_1    |    3: std::sys_common::backtrace::__rust_end_short_backtrace
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/sys_common/backtrace.rs:141:18
seed1_1    |    4: rust_begin_unwind
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:493:5
seed1_1    |    5: core::panicking::panic_fmt
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/panicking.rs:92:14
seed1_1    |    6: core::option::expect_failed
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/option.rs:1237:5
seed1_1    |    7: core::option::Option<T>::expect
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/option.rs:349:21
seed1_1    |    8: <nimiq_consensus_albatross::sync::history::HistorySync<TNetwork> as futures_core::stream::Stream>::poll_next
seed1_1    |              at /build/consensus-albatross/src/sync/history.rs:673:40
seed1_1    |    9: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.13/src/stream.rs:129:9
seed1_1    |   10: futures_util::stream::stream::StreamExt::poll_next_unpin
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/mod.rs:1415:9
seed1_1    |   11: <nimiq_consensus_albatross::sync::request_component::BlockRequestComponent<TPeer> as futures_core::stream::Stream>::poll_next
seed1_1    |              at /build/consensus-albatross/src/sync/request_component.rs:111:44
seed1_1    |   12: <nimiq_consensus_albatross::sync::block_queue::BlockQueue<TPeer,TReq> as futures_core::stream::Stream>::poll_next
seed1_1    |              at /build/consensus-albatross/src/sync/block_queue.rs:361:15
seed1_1    |   13: futures_util::stream::stream::StreamExt::poll_next_unpin
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/mod.rs:1415:9
seed1_1    |   14: <nimiq_consensus_albatross::consensus::Consensus<N> as futures_core::stream::Stream>::poll_next
seed1_1    |              at /build/consensus-albatross/src/consensus/mod.rs:336:46
seed1_1    |   15: <futures_util::stream::stream::for_each::ForEach<St,Fut,F> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/for_each.rs:71:47
seed1_1    |   16: nimiq_client::main_inner::{{closure}}::{{closure}}
seed1_1    |              at /build/client/src/main.rs:89:31
seed1_1    |   17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/future/mod.rs:80:19
seed1_1    |   18: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
seed1_1    |   19: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
seed1_1    |   20: tokio::runtime::task::core::Core<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
seed1_1    |   21: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
seed1_1    |   22: core::ops::function::FnOnce::call_once
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/ops/function.rs:227:5
seed1_1    |   23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panic.rs:344:9
seed1_1    |   24: std::panicking::try::do_call
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:379:40
seed1_1    |   25: __rust_try
seed1_1    |   26: std::panicking::try
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:343:19
seed1_1    |   27: std::panic::catch_unwind
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panic.rs:431:14
seed1_1    |   28: tokio::runtime::task::harness::Harness<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
seed1_1    |   29: tokio::runtime::task::raw::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
seed1_1    |   30: tokio::runtime::task::raw::RawTask::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
seed1_1    |   31: tokio::runtime::task::Notified<S>::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
seed1_1    |   32: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:349:13
seed1_1    |   33: tokio::coop::with_budget::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
seed1_1    |   34: std::thread::local::LocalKey<T>::try_with
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/thread/local.rs:272:16
seed1_1    |   35: std::thread::local::LocalKey<T>::with
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/thread/local.rs:248:9
seed1_1    |   36: tokio::coop::with_budget
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
seed1_1    |       tokio::coop::budget
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
seed1_1    |       tokio::runtime::thread_pool::worker::Context::run_task
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:348:9
seed1_1    |   37: tokio::runtime::thread_pool::worker::Context::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:320:24
seed1_1    |   38: tokio::runtime::thread_pool::worker::run::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:305:17
seed1_1    |   39: tokio::macros::scoped_tls::ScopedKey<T>::set
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
seed1_1    |   40: tokio::runtime::thread_pool::worker::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:302:5
seed1_1    |   41: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:281:45
seed1_1    |   42: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/task.rs:41:21
seed1_1    |   43: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
seed1_1    |   44: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
seed1_1    |   45: tokio::runtime::task::core::Core<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
seed1_1    |   46: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
seed1_1    |   47: core::ops::function::FnOnce::call_once
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/ops/function.rs:227:5
seed1_1    |   48: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panic.rs:344:9
seed1_1    |   49: std::panicking::try::do_call
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:379:40
seed1_1    |   50: __rust_try
seed1_1    |   51: std::panicking::try
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:343:19
seed1_1    |   52: std::panic::catch_unwind
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panic.rs:431:14
seed1_1    |   53: tokio::runtime::task::harness::Harness<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
seed1_1    |   54: tokio::runtime::task::raw::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
seed1_1    |   55: tokio::runtime::task::raw::RawTask::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
seed1_1    |   56: tokio::runtime::task::Notified<S>::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
seed1_1    |   57: tokio::runtime::blocking::pool::Inner::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:250:17
seed1_1    |   58: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:230:21
seed1_1    |   59: tokio::runtime::context::enter
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
seed1_1    |   60: tokio::runtime::handle::Handle::enter
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
seed1_1    |   61: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:229:17
seed1_1    |   62: std::sys_common::backtrace::__rust_begin_short_backtrace
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/sys_common/backtrace.rs:125:18
seed1_1    |   63: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/thread/mod.rs:474:17
seed1_1    |   64: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panic.rs:344:9
seed1_1    |   65: std::panicking::try::do_call
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:379:40
seed1_1    |   66: __rust_try
seed1_1    |   67: std::panicking::try
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panicking.rs:343:19
seed1_1    |   68: std::panic::catch_unwind
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/panic.rs:431:14
seed1_1    |   69: std::thread::Builder::spawn_unchecked::{{closure}}
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/thread/mod.rs:473:30
seed1_1    |   70: core::ops::function::FnOnce::call_once{{vtable.shim}}
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/core/src/ops/function.rs:227:5
seed1_1    |   71: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/alloc/src/boxed.rs:1546:9
seed1_1    |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/alloc/src/boxed.rs:1546:9
seed1_1    |       std::sys::unix::thread::Thread::new::thread_start
seed1_1    |              at /rustc/c755ee4ce8cae6ea977d65a0288480940db721d9/library/std/src/sys/unix/thread.rs:71:17
seed1_1    |   72: start_thread
seed1_1    |   73: clone
```

**Comment by viquezclaudio** [comment] 2021-11-16 19:15
This happened again in this CI run:
https://github.com/nimiq/core-rs-albatross/runs/4228037023?check_suite_focus=true

**Comment by fiaxh** [comment] 2021-11-22 17:04
Backup of the CI logs: [reconnect-test-logs-with-spammer.zip](https://github.com/nimiq/core-rs-albatross/files/7582923/reconnect-test-logs-with-spammer.6.zip)

**Comment by viquezclaudio** [comment] 2022-03-11 15:05
Closing it because of Duplicate of #633

**Closed as completed by viquezclaudio** 2022-03-11 15:05 UTC
Labels: bug
