### ISSUE TITLE
CI Run - Panic `Failed to find main chain predecessor while reverting blocks: BlockNotFound`

### ISSUE THREAD

**Issue by ii-cruz** [nimiq/core-rs-albatross#2789] opened 2024-07-29 15:59 UTC
Panic validator 2

CI run https://github.com/nimiq/core-rs-albatross/actions/runs/9909303370

**Comment by styppo** [comment] 2024-07-29 16:06
Duplicate of #2740, this is already fixed.

**Closed as completed by styppo** 2024-07-29 16:06 UTC
Labels: bug
