### ISSUE TITLE
Local receiver for channel already registered: type_id = 201

### ISSUE THREAD

**Issue by fiaxh** [nimiq/core-rs-albatross#349] opened 2021-09-23 17:38 UTC
```
 2021-09-23 18:38:18.631 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Local receiver for channel already registered: type_id = 201': /home/user/Devel/core-rs2/network-libp2p/src/message/dispatch.rs:226
   0: log_panics::init::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:521:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:517:5
   5: std::panicking::begin_panic_fmt
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:460:5
   6: nimiq_network_libp2p::message::dispatch::MessageDispatch<C>::receive
             at network-libp2p/src/message/dispatch.rs:226:13
   7: <nimiq_network_libp2p::message::peer::Peer as nimiq_network_interface::peer::Peer>::receive
             at network-libp2p/src/message/peer.rs:106:9
   8: nimiq_network_interface::request_response::RequestResponse<P,Req,Res>::new
             at network-interface/src/request_response.rs:50:22
   9: nimiq_consensus::consensus_agent::ConsensusAgent<P>::new
             at consensus/src/consensus_agent.rs:50:37
  10: <nimiq_consensus::sync::history::HistorySync<TNetwork> as nimiq_consensus::sync::request_component::HistorySyncStream<<TNetwork as nimiq_network_interface::network::Network>::PeerType>>::add_peer
             at consensus/src/sync/history.rs:970:30
  11: <nimiq_consensus::sync::request_component::BlockRequestComponent<TPeer> as nimiq_consensus::sync::request_component::RequestComponent<TPeer>>::put_peer_into_sync_mode
             at consensus/src/sync/request_component.rs:97:9
  12: nimiq_consensus::sync::block_queue::Inner<N>::on_block_announced
             at consensus/src/sync/block_queue.rs:140:17
  13: <nimiq_consensus::sync::block_queue::BlockQueue<N,TReq> as futures_core::stream::Stream>::poll_next
             at consensus/src/sync/block_queue.rs:570:21
  14: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/stream/stream/mod.rs:1474:9
  15: <nimiq_consensus::consensus::Consensus<N> as core::future::future::Future>::poll
             at consensus/src/consensus/mod.rs:350:46
  16: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/core.rs:161:17
  17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/loom/std/unsafe_cell.rs:14:9
  18: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/core.rs:151:13
  19: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:461:19
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/core/src/panic/unwind_safe.rs:271:9
  21: std::panicking::try::do_call
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:403:40
  22: __rust_try
  23: std::panicking::try
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:367:19
  24: std::panic::catch_unwind
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panic.rs:129:14
  25: tokio::runtime::task::harness::poll_future
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:449:18
  26: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:98:27
  27: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:53:15
  28: tokio::runtime::task::raw::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/raw.rs:113:5
  29: tokio::runtime::task::raw::RawTask::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/raw.rs:70:18
  30: tokio::runtime::task::LocalNotified<S>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/mod.rs:343:9
  31: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:431:21
  32: tokio::coop::with_budget::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:106:9
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/thread/local.rs:399:16
  34: std::thread::local::LocalKey<T>::with
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/thread/local.rs:375:9
  35: tokio::coop::with_budget
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:99:5
      tokio::coop::budget
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:76:5
      tokio::runtime::thread_pool::worker::Context::run_task
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:407:9
  36: tokio::runtime::thread_pool::worker::Context::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:374:24
  37: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:359:17
  38: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/macros/scoped_tls.rs:61:9
  39: tokio::runtime::thread_pool::worker::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:356:5
  40: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/worker.rs:335:45
  41: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/task.rs:42:21
  42: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/core.rs:161:17
  43: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/loom/std/unsafe_cell.rs:14:9
  44: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/core.rs:151:13
  45: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:461:19
  46: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/core/src/panic/unwind_safe.rs:271:9
  47: std::panicking::try::do_call
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:403:40
  48: __rust_try
  49: std::panicking::try
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:367:19
  50: std::panic::catch_unwind
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panic.rs:129:14
  51: tokio::runtime::task::harness::poll_future
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:449:18
  52: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:98:27
  53: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/harness.rs:53:15
  54: tokio::runtime::task::raw::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/raw.rs:113:5
  55: tokio::runtime::task::raw::RawTask::poll
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/raw.rs:70:18
  56: tokio::runtime::task::UnownedTask<S>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/task/mod.rs:379:9
  57: tokio::runtime::blocking::pool::Inner::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/pool.rs:265:17
  58: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/pool.rs:245:17
  59: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/sys_common/backtrace.rs:125:18
  60: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/thread/mod.rs:481:17
  61: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/core/src/panic/unwind_safe.rs:271:9
  62: std::panicking::try::do_call
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:403:40
  63: __rust_try
  64: std::panicking::try
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:367:19
  65: std::panic::catch_unwind
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panic.rs:129:14
  66: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/thread/mod.rs:480:30
  67: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/core/src/ops/function.rs:227:5
  68: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/sys/unix/thread.rs:106:17
  69: start_thread
             at ./nptl/./nptl/pthread_create.c:463:8
  70: clone
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by viquezclaudio** [comment] 2021-11-25 23:55
This error has not been observed in any of our CI runs from last months, closing it since its not reproducible anymore

**Closed as completed by viquezclaudio** 2021-11-25 23:55 UTC
Labels: bug, needs validation
