### ISSUE TITLE
Nimiq-client cannot write "signing_key.dat"

### ISSUE THREAD

**Issue by joeleol** [nimiq/core-rs-albatross#2416] opened 2024-05-01 10:11 UTC
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 0.21.0
- Browser version(s): N/A
- Devices/Simulators/Machine affected: Validators
- Reproducible in the testnet? (Yes/No): Yes
- Related issues: None that I can find

## Bug report

While setting up a new validator on a fresh Ubuntu VPS, I ran cargo run and it exits due to 'IO Error: No such file or directory'

#### Expected behavior

"signing_key.day" should be written to ~/core-rs-albatross   (I assume, I cannot find the path details anywhere)

#### Actual behavior

See bug report

#### Steps to reproduce

See bug report

#### Crash log? Screenshots? Videos? Sample project?

2024-05-01T10:06:08.750756035Z DEBUG file_store           | Reading from: /home/ubuntu/.nimiq/peer_key.dat
2024-05-01T10:06:08.750835398Z INFO  client               | Identity public key: PublicKey { publickey: Ed25519(PublicKey(compressed): 1bf33e471dbf3751ee156eb54b30edcc5d371012cd3bc5e1ca192d8ef1236a96) }
2024-05-01T10:06:08.750876417Z INFO  client               | PeerId: 12D3KooWBhUJUy1H44Qs2jBxwdVcVbimSZEHWhzTdYsaUenjyBgR
2024-05-01T10:06:08.750899212Z INFO  client               | Client configured as a full node
2024-05-01T10:06:08.750998003Z DEBUG client               | Listen addresses addresses=["/ip4/0.0.0.0/tcp/8443/ws"]
2024-05-01T10:06:08.751019585Z DEBUG client               | Advertised addresses addresses=Some(["/ip4/51.68.188.164/tcp/8444/ws"])
2024-05-01T10:06:08.752167188Z INFO  libp2p_swarm         | local_peer_id=12D3KooWBhUJUy1H44Qs2jBxwdVcVbimSZEHWhzTdYsaUenjyBgR
2024-05-01T10:06:08.752260830Z INFO  config               | Opening database: testalbatross-full-consensus
2024-05-01T10:06:08.753631615Z INFO  database             | MDBX memory map size cur_mapsize=1099511627776
2024-05-01T10:06:08.769758098Z INFO  zkp_component        | No zk proof found on the db
2024-05-01T10:06:08.769955289Z TRACE sync_queue           | Creating SyncQueue for nimiq_consensus::sync::live::block_queue::block_request_component::MissingBlockResponse with 0 ids and 0 peers
2024-05-01T10:06:08.769988013Z TRACE sync_queue           | Creating SyncQueue for (nimiq_consensus::sync::live::state_queue::ResponseChunk, nimiq_consensus::sync::live::state_queue::RequestChunk, libp2p_identity::peer_id::PeerId) with 0 ids and 0 peers
2024-05-01T10:06:08.770019944Z TRACE sync_queue           | Creating SyncQueue for (nimiq_consensus::messages::RequestHistoryChunk, core::result::Result<nimiq_consensus::messages::HistoryChunk, nimiq_consensus::messages::HistoryChunkError>, libp2p_identity::peer_id::PeerId) with 0 ids and 0 peers
2024-05-01T10:06:08.770213990Z DEBUG file_store           | Writing to file path="signing_key.dat"
2024-05-01T10:06:08.770594458Z ERROR logging              | File store error: IO error: No such file or directory (os error 2)
2024-05-01T10:06:08.770613305Z ERROR logging              |   caused by
2024-05-01T10:06:08.770621199Z ERROR logging              |     IO error: No such file or directory (os error 2)
2024-05-01T10:06:08.770643653Z ERROR logging              |     No such file or directory (os error 2)

**Comment by Eligioo** [comment] 2024-05-01 10:15
Duplicate of #2400 and fixed in #2401. It means `~/.nimiq` is missing.

**Comment by joeleol** [comment] 2024-05-01 10:22
~/.nimiq is present and also 777'd to be sure

You can also see at the start of the client it reads the peer_key.dat from ~/.nimiq

**Comment by Eligioo** [comment] 2024-05-01 10:27
With #2401 and #2414, it will be made sure that the folder you've configured for you signing_key will be created before anything will be written to it.

**Comment by joeleol** [comment] 2024-05-01 10:36
Update: I deleted my ~/.nimiq folder, ran the client again, it creates the folder (and puts the peer_key and database in there, but throws the same error regarding the other keys...

From memory, the three *_key.dat files used to be created in ~/core-rs-albatross other than peer_key.dat, which was always created in ~/.nimiq

**Comment by hrxi** [comment] 2024-05-01 11:50
Is this issue reproducible on the newest albatross branch? @joeleol

**Comment by joeleol** [comment] 2024-05-01 11:52
Yes, @Eligioo helped me solve it by setting the key paths in the client.toml as absolute paths. I have been playing with the testnet over 1 year, and this is the first time I saw this, so I guess it was recently introduced.

**Comment by joeleol** [comment] 2024-05-01 12:41
I tried to figure out where it's trying to write to, but it's not any of three usual candidates: ~/.nimiq  ~/core-rs-albatross and ~/.config/nimiq  I even created those three and 777'd them all - error is still there.

**Comment by hrxi** [comment] 2024-05-01 12:57
You can probably figure out where they try to write by using `strace`.

**Comment by hrxi** [comment] 2024-05-01 13:19
Ok, the problem is probably exactly the code introduced in #2401.

The code will take `"signing_key.dat"`, try to obtain its parent directory, which will be `Some("")`: [`Path::parent` documentation](https://doc.rust-lang.org/std/path/struct.Path.html#method.parent). Then `std::fs::create_dir` will fail with "No such file or directory" when being passed the empty string.

This will get fixed by #2414, first, because it doesn't check for the existence of the parent directory, and second, because `create_dir_all` works on the empty string.

**Comment by joeleol** [comment] 2024-05-01 13:20
I have just tested your branch minor_fixes56 and #2401 does fix this.

**Closed as completed** 2024-05-02 13:23 UTC
